<?php

namespace ContainerN2d2JEx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MRyu9nEService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.mRyu9nE' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.mRyu9nE'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'task' => ['privates', '.errored..service_locator.mRyu9nE.App\\Entity\\Task', NULL, 'Cannot autowire service ".service_locator.mRyu9nE": it references class "App\\Entity\\Task" but no such service exists.'],
        ], [
            'task' => 'App\\Entity\\Task',
        ]);
    }
}
