<?php

namespace ContainerN2d2JEx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BU8nL9LService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.bU8nL9L' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.bU8nL9L'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'project' => ['privates', '.errored..service_locator.bU8nL9L.App\\Entity\\Project', NULL, 'Cannot autowire service ".service_locator.bU8nL9L": it references class "App\\Entity\\Project" but no such service exists.'],
        ], [
            'project' => 'App\\Entity\\Project',
        ]);
    }
}
