<?php

namespace ContainerY7X3j9M;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EMcv3XiService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.EMcv3Xi' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.EMcv3Xi'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'taskRepository' => ['privates', 'App\\Repository\\TaskRepository', 'getTaskRepositoryService', true],
        ], [
            'taskRepository' => 'App\\Repository\\TaskRepository',
        ]);
    }
}
