<?php

namespace ContainerY7X3j9M;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProject2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.bU8nL9L.App\Entity\Project' shared service.
     *
     * @return \App\Entity\Project
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.bU8nL9L": it references class "App\\Entity\\Project" but no such service exists.');
    }
}
